#pragma once

#define SMALL_STEP_PDM_CLK_GPIO 4
#define SMALL_STEP_PDM_DATA_GPIO 5

#define SMALL_STEP_SAMPLE_RATE_HZ 16000U
#define SMALL_STEP_RECORD_SECONDS 30U
#define SMALL_STEP_SPEECH_RMS_THRESHOLD 350U

#define SMALL_STEP_HEARTBEAT_INTERVAL_SECONDS 60U
#define SMALL_STEP_RETRY_INTERVAL_SECONDS 15U
#define SMALL_STEP_HTTP_TIMEOUT_MILLISECONDS 60000

#define SMALL_STEP_PENDING_WAV_PATH "/retry/pending.wav"
#define SMALL_STEP_PENDING_WAV_TEMP_PATH "/retry/pending.wav.tmp"
#define SMALL_STEP_PENDING_ID_PATH "/retry/pending.id"
#define SMALL_STEP_PENDING_ID_TEMP_PATH "/retry/pending.id.tmp"
